development:
  adapter: postgresql
  encoding: unicode
  database: push_back_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: push_back_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: push_back_production
  pool: 5
